### ISSUE TITLE
add tel:// links

### ISSUE THREAD

**Issue by xyzshantaram** [shantaram3013/covid19-resource-site#21]

**Comment by Krishna-Sivakumar** [comment]
for what?

**Comment by xyzshantaram** [comment]
phone numbers. so the number is called when the link is clicked

**Comment by gomahan** [comment]
Can you please add me as a contributor ? I will the try to fix the issues listed here

**Comment by xyzshantaram** [comment]
Hi! We don't have a policy of adding new people as contributors, for fear of vandalism.

However you're welcome to fork the repo and make a pull request, and we'll review and merge it ASAP if it is up to our standards.

Thanks!

**Comment by gomahan** [comment]
Raised Pull req for the same

**Comment by xyzshantaram** [comment]
Thanks, reviewed and requested changes.

**Comment by xyzshantaram** [comment]
Fixed by @gomahan in #33.
