### ISSUE TITLE
Load resources when needed

### ISSUE THREAD

**Issue by Krishna-Sivakumar** [shantaram3013/covid19-resource-site#27]
We need to load resources when they're actually need instead of loading them all at once at the start.
We'll implement this inside the ```state-dropdown```'s onChange event, and the ```resource-btn```'s onClick event.

**Comment by xyzshantaram** [comment]
it would speed up loading by a lot, i agree

**Comment by xyzshantaram** [comment]
fixed in 7c7e9464c83405ab722298d56bf0743e79b06f1d.
