### ISSUE TITLE
Button Colors

### ISSUE THREAD

**Issue by defenestrat0r** [shantaram3013/covid19-resource-site#31]
Might want to consider a different colour scheme for the buttons. Red is an alert/danger color and might send the wrong message to users. 

Consider not using separate colours on the buttons to avoid confusion. Users don't need to know what's important. They're coming here to look for what they need, they already know what's important.

**Comment by xyzshantaram** [comment]
hahaha bg-danger go brrrrr

**Comment by xyzshantaram** [comment]
jokes aside, i'll get this implemented after i fix #28

**Comment by defenestrat0r** [comment]
❤️

**Comment by xyzshantaram** [comment]
also i'm pretty colorblind so it looked more green/maroon to me than red :clown_face:

**Comment by defenestrat0r** [comment]
Dang, didn't know that. Get someone else to deal with the colours xD

**Comment by xyzshantaram** [comment]
Fixed in 9059ed20a8b084504b7158851695cd8ec6b1737e.
